




<?php if(!isset($_POST['valider']))
	  {?>	
	    <h2>Affichage des vols</h2>
		<table id="tableauTitreVol">
			<tr>
				<th > Commentaires </th>
				<th > Id Journal de bord </th>				
				<th>  Numero de vol </th>		
				<th > </th>
			</tr>
		</table>

		<?php 
			//$tableau = $this->tableau;
			$formulaire = $this->formulaire;
			$form = $this->formAjoutCommentaire;
			$lesJournaux = $this->lesJournaux;
			$idJournal=$this->idJournal;
			$numVol=$this->numVol;
			$paginator=$this->paginator;
			$i=0;
					
			echo $this->formulaire; 
		?>
			
		<table id="tableauInfoVol">
		<?php 
				
			  	foreach($lesJournaux as $unJournal) 
			  	{
			  		if(isset($idJournal[$unJournal['idJournalDeBord']]))
					{	
				  		$id=$unJournal['idJournalDeBord'];
				  		$i++; ?>
						<tr>
							<td><?php echo $idJournal[$unJournal['idJournalDeBord']]; ?></td>		
							<td><?php echo $numVol[$unJournal['idJournalDeBord']]; ?></td>								   					   	
					   		<td><a  href="<?php echo $this->baseUrl('logistique/ajoutcommentaire')."?idJournalDeBord=$id"?>">Ajouter un commentaire</a></td>				   			
						</tr>			
		  <?php 	}
				}?> 						
		</table>
		
	<?php }
	if(isset($paginator))
	{
		echo $this->paginationControl($paginator,'All', 'paginationcontrole.phtml');
	}?>