<h2>Affichage de commentaires</h2>


<?php if(!isset($_POST['valider']))
	  {?>
		<table id="tableauTitreVol">
			<tr>
				<th > </th>
				<th > Id Journal de bord </th>	
				<th > </th>
				<th>  Numero de vol </th>		
			</tr>
		</table>

		<?php 
			$tableau = $this->tableau;
			$formulaire = $this->formulaire;
			$listeNumVol = $this->listeNumVol;
			$i=0;
					
			echo $this->formulaire; 
		?>
			
		<table id="tableauInfoVol">
		<?php 
				$lesJournaux = $this->lesJournaux; 
			  	foreach($lesJournaux as $unJournal) 
			  	{
			  		$i++; ?>
					<tr>
						<td><?php echo $unJournal->idJournalDeBord; ?></td>						
				   		<td><?php echo $listeNumVol[$i][0];?></td>	
					</tr>
		  <?php }?> 						
		</table>
	<?php }?>
