<ul>
	<li>
		<a href="<?php echo $this->baseUrl('logistique/index'); ?>?valeur=afficher">
			Liste des vols
		</a>
	</li>		
</ul>

<?php 
$tableauCom = $this->tableauCom;
$compteur = $this->compteur;

 if(count($tableauCom) > 0)
 { ?>
	<div id="tableauxSupprVol">		
		<table id="tableauTitreVol">
			<tr>
				<th >idCommentaireVol</th>
				<th >idJournalDeBord</th>
				<th >titre</th>
				<th >commentaire</th>								
			</tr>
		
				<?php 
					for ($ii=1; $ii<=$compteur; $ii++)
					{
				?>  	<tr>
						<?php 
							for ($jj=0;$jj<4;$jj++)
							{
						?>
							<td>
								<?php echo $tableauCom[$ii][$jj];?>
							</td>
						<?php 			
							}$jj=0;
						?>
						</tr>
				<?php 	
					}
				?>		
		</table>		
	</div>
<?php } ?>
