<ul>
	<li>
		<a href="<?php echo $this->baseUrl('logistique/index'); ?>?valeur=afficher">
			Vols
		</a>
	</li>	
</ul>


<?php $tableauCom = $this->tableauCom;
$compteur = $this->compteur;
if(count($tableauCom) > 0){ ?>
	<div id="tableauxSupprVol">
		
		<table id="tableauTitreVol">
			<tr>
				<th >idCommentaireVol</th>
				<th >idJournalDeBord</th>
				<th >titre</th>
				<th >commentaire</th>
				<th >idVol</th>
				
			</tr>
		
				<?php 
					for ($ii=1; $ii<=$compteur; $ii++)
					{
				?>
						<tr>
						<?php 
							for ($jj=0;$jj<5;$jj++){
						?>
							<td>
								<?php echo $tableauCom[$ii][$jj];?>
							</td>
						<?php 			
							}$jj=0;
						?>
						</tr>
				<?php 	
					}
				?>
					
			
		</table>
		
	</div>
<?php } ?>

<?php $tableau = $this->tableau;

if(count($tableau) > 0){ ?>
	
			
		<table>	
			<tr><?php for ($i=0; $i<count($tableau); $i++) 
			  {?>				
				<td><?php echo $tableau[$i] ;?></td>						
		<?php } ?>
				
			</tr>
		</table>
		
	</div>
<?php } ?>