<?php 
echo $this->doctype();
?>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Insset-airlines</title>
	<?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
	<link href="<?php echo $this->baseUrl('/css/style.css')?>" media="screen" rel="stylesheet" type="text/css" />
</head>
<header>
</header>
<body>

	<div id="contenu">
	<?php echo $this->layout()->content; ?>
	</div>

</body>

<footer>
	<div id="pied">
		<p id="copyright">Grp 4 &copy; 2012</p>
	</div>
</footer>

</html>
