<?php 
//on récupère les infos du controlleur
$formulaire = $this->formulaire;
$formulaireChoix = $this->formulaireChoix;
$aujourdhui = $this->aujourdhui;
$jour = $this->jour;
$aeroport = $this->aeroport;
$aero = $this->aero;

$journalsDate = $this->journalsDate;
$idVolsDate = $this->idVolsDate;
$numVolsDate = $this->numVolsDate;
$aeroDepartVolsDate = $this->aeroDepartVolsDate;
$aeroArriveeVolsDate = $this->aeroArriveeVolsDate;
$lesVolsDate = $this->lesVolsDate;

$aeroportDepart = $this->aeroportDepart;
$journalsJour = $this->journalsJour;
$idVolsJour = $this->idVolsJour;
$numVolsJour = $this->numVolsJour;
$aeroDepartVolsJour = $this->aeroDepartVolsJour;
$aeroArriveeVolsJour = $this->aeroArriveeVolsJour;
$lesVolsJour = $this->lesVolsJour;


$message = $this->message;

?>

	
<div class = "formulaireNico plusHaut">
<?php if(isset($message)){?>
<div class="mess">
<?php echo $message;?>
</div>
<?php }?>
<?php if(isset($aero)){ ?> 
	<div class ="imgRetour">
		<a href="<?php echo $this->baseUrl('planning/creerplanning'); ?>?retour=oui">
			<img src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" />
		</a>
	</div>
<?php }?>
	<div class = "contenuFormulaireNico">
		<?php 
			echo $formulaireChoix;
		?>
	</div>
</div>


	
		
<?php if(isset($aujourdhui)) { ?>
<div class = "formulaireNico plusBas">
<div class ="contenuFormulaireNico2">
<p>Pour le <?php echo $aujourdhui; ?> <br/>Pour l'aéroport <?php echo $aeroport; ?> : </p>

<?php }?>

<?php if(isset($lesVolsDate)) 
{ 
	foreach($lesVolsDate as $unVol) 
	{ 
		if($journalsDate[$unVol['idVol']] == 'existe pas')
		{ $erreur = 1;?>
		<div class="unVolAfficher">
		Vol de <?php echo $aeroDepartVolsDate[$unVol['idVol']]; ?> à <?php echo $aeroArriveeVolsDate[$unVol['idVol']]; ?> : <br/>
		<a href="<?php echo $this->baseUrl('planning/volacreer'); ?>?numerovol=<?php echo $idVolsDate[$unVol['idVol']]; ?>&date=<?php echo $aujourdhui; ?>">
		Créer le vol n° <?php echo $numVolsDate[$unVol['idVol']]; ?>
		</a></div>

<?php  }else {$erreur = 1;}}} ?>

<?php if(isset($lesVolsJour)) 
{ 
	foreach($lesVolsJour as $unVol) 
	{ 
			if($journalsJour[$unVol['idVol']] == 'existe pas')
			{ ?>
			<div class="unVolAfficher">
		Vol de <?php echo $aeroDepartVolsJour[$unVol['idVol']]; ?> à <?php echo $aeroArriveeVolsJour[$unVol['idVol']]; ?> : <br/>
		<a href="<?php echo $this->baseUrl('planning/volacreer'); ?>?numerovol=<?php echo $idVolsJour[$unVol['idVol']]; ?>&date=<?php echo $aujourdhui; ?>">
		Créer le vol n° <?php echo $numVolsJour[$unVol['idVol']]; ?>
		</a></div>
<?php }else {$erreur2 = 1;}}} 
if(isset($erreur)){ if(isset($erreur2)){?>
aucun vol n'est prévu
<?php }}?>
<?php if(isset($aujourdhui)) { ?>
</div></div>
<?php }?>