<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('planning/creerplanning/'); ?>">
						Créer le planning
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('planning/modifierplanning'); ?>">
						Modifier le planning
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>
<?php 
$message = $this->message;
?>

<?php if(isset($message)){?>
<div class="mess">
<?php echo $message;?>
</div>
<?php }?>