<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('planning/index/'); ?>?valeur=creer">
						Créer le planning
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('planning/index'); ?>?valeur=modifier">
						Modifier le planning
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>