<?php 
//on récupère les infos du controlleur
$volAPlannifier = $this->leVol;
$idAvion = $this->lesAvions;
$idPilote = $this->lesPilotes;
$dateDuVolAPlannifier = $this->datePrevu;
$monAvion = $this->monAvion;
$message = $this->message;
?>
<div class = "formulaireNico plusBas">
<div class ="contenuFormulaireNico2">

Vol: <span class ="centrer"><?php echo $volAPlannifier;?></span> <br/>
Date prevu: <span class ="centrer"><?php echo $dateDuVolAPlannifier;?></span> <br/>
<?php if(isset($monAvion)){?>
Avion choisie: <span class ="centrer"><?php echo $monAvion;?></span> <br/>

<?php }?>
<?php if(isset($message)){?>
<?php echo $message;?> <br/>
<?php }?>

<?php 
$formulaire = $this->formulaire; 
echo $formulaire;
?>
</div>
</div>