<?php 
//on récupère les infos du controlleur
$volAPlannifier = $this->leVol;
$idAvion = $this->lesAvions;
$idPilote = $this->lesPilotes;
$dateDuVolAPlannifier = $this->datePrevu;
$monAvion = $this->monAvion;
$message = $this->message;
?>

Vol: <?php echo $volAPlannifier;?> <br/>
Date prevu: <?php echo $dateDuVolAPlannifier;?> <br/>
<?php if(isset($monAvion)){?>
Avion choisie: <?php echo $monAvion;?> <br/>
<?php }?>
<?php if(isset($message)){?>
<?php echo $message;?> <br/>
<?php }?>

<?php 
$formulaire = $this->formulaire; 
echo $formulaire;
?>