<?php 
//on récupère les infos du controlleur
$volAPlannifier = $this->leVol;
$idAvion = $this->lesAvions;
$idPilote = $this->lesPilotes;
$dateDuVolAPlannifier = $this->datePrevu;
?>

Vol: <?php echo $volAPlannifier;?> <br/>
date prevu: <?php echo $dateDuVolAPlannifier;?> <br/>
________________________________________________<br/>
Les Avions disponibles: <br/>
<?php  if(isset($idAvion)) { foreach($idAvion as $unAvion) { ?>
<?php echo $unAvion; ?><br/>
<?php } }?>
________________________________________________<br/>
Les Pilotes et copilotes disponibles: <br/>
<?php  if(isset($idPilote)) { foreach($idPilote as $unPilote) { ?>
<?php echo $unPilote; ?><br/>
<?php } }?>

<?php 
$formulaire = $this->formulaire; 
echo $formulaire;
?>