<ul>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=index">
			Accueil
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=commercial">
			Service Commercial
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=strategique">
			Service Stratégique
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=technique">
			Service Technique
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=logistique">
			Service Logistique
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=drh">
			Direction des ressources humaines
		</a>
	</li>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>?menu=maintenance">
			Service de Maintenance
		</a>
	</li>
</ul>