<ul>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 1)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Service Commercial
		</a>
	</li>
	<?php }?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 2)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Service Stratégique
		</a>
	</li>
	<?php }?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 3)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Service Technique
		</a>
	</li>
	<?php }?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 4)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('logistique/index'); ?>">
			Service Logistique
		</a>
	</li>
	<?php }?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 5)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Direction des ressources humaines
		</a>
	</li>
	<?php } ?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 6)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Service de Maintenance
		</a>
	</li>
	<?php } ?>
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 8)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Service d'exploitation
		</a>
	</li>
	
	
	<?php if(($_SESSION['Zend_Auth']['storage']->service == 7)||($_SESSION['Zend_Auth']['storage']->service == 9)){?>
	<li>
		<a href="<?php echo $this->baseUrl('index/index'); ?>">
			Gestion du planning
		</a>
	</li>
	<?php } ?>
	<?php } ?>
</ul>
