<center>
<table class="tablemenu">
	<tr>
		<td>
			<p class="buttonSousMenu">
				<a href="#?w=500" rel="popupajoutaeroport" class="poplight">Ajouter un aéroport</a>			
			</p>
		</td>
	</tr>
</table>

<br /><br />
<table class="avion">
	<thead>
		<tr> 	
			<th>Nom</th>
			<th>Trigramme</th>
			<th>Longueur de la piste</th>
			<th>Ville</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php 
	$lesaeroports = $this->lesaeroports;
	$ville = new Ville();
	foreach ($lesaeroports as $unaeroport)
	{
		$laville = $ville->selectOne($unaeroport['idVille']);
?>
		<tr>
			<td><?= $unaeroport['nomAeroport'] ;?></td>
			<td><?= $unaeroport['trigramme'] ;?></td>
			<td><?= $unaeroport['longueurPiste']; ?></td>
			<td><?= $laville[0]['nomVille'] ;?></td>
			<td><a href="/admin/modifieraeroport?idAeroport=<?= $unaeroport['idAeroport']; ?>"><img src="/img/modif.gif" alt="modif" /></a></td>
		</tr>
<?php }?>
	</tbody>
</table>
<div id="popupajoutaeroport" class="popup_block">
	<?php echo $this->formajoutaeroport;?>           
</div>
<br />
<?php if($lesaeroports != NULL && count($lesaeroports)>15){ echo $this->paginationControl($lesaeroports,'All', 'paginationcontroleavion.phtml');}?>
<br /><br /></center>
<a href="/admin/index">Retour</a>