<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/ville/'); ?>">
						Gérer les villes
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/pays'); ?>">
						Gérer les pays
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/aeroport'); ?>">
						Gérer les aéroports
					</a>
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/user'); ?>">
						Gérer les utilisateurs
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/brevet'); ?>">
						Gérer les brevets
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('admin/modele'); ?>">
						Gérer les modèles
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>
