<center>
<table class="tablemenu">
	<tr>
		<td>
			<p class="buttonSousMenu">
				<a href="#?w=500" rel="popupajoutpays" class="poplight">Ajouter un pays</a>
			</p>
		</td>
	</tr>
</table>

<br /><br />

<table class="avion" id="tableauInfoVolMath">
	<thead>
		<tr> 	
			<th>Nom</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php 
	$lespays = $this->lespays;
	foreach ($lespays as $unpays)
	{
?>
		<tr>
			<td><?= $unpays['nomPays'] ;?></td>
			<td><a href="/admin/modifierpays?idPays=<?= $unpays['idPays']; ?>"><img src="/img/outil.png" alt="modif"/></a></td>
		</tr>
<?php }?>
	</tbody>
</table>
<div id="popupajoutpays" class="popup_block">
	<?php echo $this->formajoutpays;?>           
</div>
<br />
<?php if($lespays != NULL){ echo $this->paginationControl($lespays,'All', 'paginationcontroleavion.phtml');}?>
<br /><br /></center>
<a href="/admin/index"><img style="width:70px;" src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" /></a>