<center>
<table class="tablemenu">
	<tr>
		<td>
			<p class="buttonSousMenu">
				<a href="#?w=500" rel="popupajoutuser" class="poplight">Ajouter un utilisateur</a>
			</p>
		</td>
	</tr>
</table>

<br /><br />

<table class="avion" id="tableauInfoVolMath">
	<thead>
		<tr>
			<th></th>
			<th>Nom</th>
			<th>Prenom</th>
			<th>Email</th>
			<th>Date de naissance</th>
			<th>Service</th>
			<th>Aeroport</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php 
	$lesusers = $this->lesusers;
	$service = new Service();
	$aeroport = new Aeroport();
	foreach ($lesusers as $unuser)
	{
		$leservice = $service->selectOne($unuser['service']);
		$laeroportDattache = $aeroport->selectOne($unuser['idAeroport']);
?>
		<tr>
	    	<td><a href="/admin/supprimeruser?idUser=<?= $unuser['idUser']; ?>" onclick="return confirm('Etes-vous sûr de vouloir supprimer cet utilisateur ?');"><img src="<?php echo $this->baseUrl('/img/viderFiltre.png'); ?>" alt="vider filtre" width="50px" height="50px" /></a></td>
			<td><?= $unuser['nomUser'] ;?></td>
			<td><?= $unuser['prenomUser'] ;?></td>
			<td><?= $unuser['email']; ?></td>
			<td><?= $unuser['dateNaissance'] ;?></td>
			<td><?= $leservice[0]['nomService'] ;?></td>
			<td><?= ucfirst ($laeroportDattache[0]['nomAeroport']);?></td>
			<td><a href="/admin/modifieruser?idUser=<?= $unuser['idUser']; ?>"><img src="/img/outil.png" alt="modif"/></a></td>
		</tr>
<?php }?>
	</tbody>
</table>
<div id="popupajoutuser" class="popup_block">
	<?php echo $this->formajoutuser;?>           
</div>
<br />
<?php if($lesusers != NULL){ echo $this->paginationControl($lesusers,'All', 'paginationcontroleavion.phtml');}?>
<br /><br /></center>
<a href="/admin/index"><img style="width:70px;" src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" /></a>