<center>
<table class="tablemenu">
	<tr>
		<td>
			<p class="buttonSousMenu">
				<a href="#?w=500" rel="popupajoutville" class="poplight">Ajouter une ville</a>
			</p>
		</td>
	</tr>
</table>

<br /><br />

<table class="avion" id="tableauInfoVolMath">
	<thead>
		<tr> 	
			<th>Nom</th>
			<th>Code postal</th>
			<th>Pays</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php 
	$lesvilles = $this->lesvilles;
	$pays = new Pays();
	foreach ($lesvilles as $uneville)
	{
		$lepays = $pays->selectOne($uneville['idPays']);
?>
		<tr>
			<td><?= $uneville['nomVille'] ;?></td>
			<td><?= $uneville['cpVille'] ;?></td>
			<td><?= $lepays[0]['nomPays'] ;?></td>
			<td><a href="/admin/modifierville?idVille=<?= $uneville['idVille']; ?>"><img src="/img/outil.png" alt="modif"/></a></td>
		</tr>
<?php }?>
	</tbody>
</table>
<div id="popupajoutville" class="popup_block">
	<?php echo $this->formajoutville;?>           
</div>
<br />
<?php if($lesvilles != NULL){ echo $this->paginationControl($lesvilles,'All', 'paginationcontroleavion.phtml');}?>
<br /><br /></center>
<a href="/admin/index"><img style="width:70px;" src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" /></a>