<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('commercial/index'); ?>?valeur=afficher">
						Liste des réservations
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('commercial/index'); ?>?valeur=ajout">
						Ajouter une réservation
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>
