<?php if ($this->pageCount): ?>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('page' => $this->first)); ?>?valeur=afficher">
        <img src="<?php echo $this->baseUrl('/img/debut.png'); ?>" alt="page precedente" />
      </a> 
    <?php else: ?>
     <?php endif; ?>
     
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('page' => $this->previous)); ?>?valeur=afficher">
       <img src="<?php echo $this->baseUrl('/img/gauche.png'); ?>" alt="page precedente" />
      </a>
    <?php else: ?>
     <?php endif; ?>
     
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('page' => $this->next)); ?>?valeur=afficher">
        <img src="<?php echo $this->baseUrl('/img/droite.png'); ?>" alt="page precedente" />
      </a> 
    <?php else: ?>
    <?php endif; ?>
     
    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('page' => $this->last)); ?>?valeur=afficher">
        <img src="<?php echo $this->baseUrl('/img/fin.png'); ?>" alt="page precedente" />
      </a>
    <?php else: ?>
    <?php endif; ?>
     
    </div>
    <?php endif; ?>