<div class="centrage">
	<?php if ($this->pageCount): ?>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
        <img style="width: 50px;" src="<?php echo $this->baseUrl('/img/debut.png'); ?>" alt="page precedente" />
      </a> 
    <?php else: ?>
      <span class="disabled"><img style="width: 50px;" src="<?php echo $this->baseUrl('/img/debut.png'); ?>" alt="page precedente" /></span> 
    <?php endif; ?>
     
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
        <img style="width: 50px;" src="<?php echo $this->baseUrl('/img/gauche.png'); ?>" alt="page precedente" />
      </a> 
    <?php else: ?>
      <span class="disabled"><img style="width: 50px;" src="<?php echo $this->baseUrl('/img/gauche.png'); ?>" alt="page precedente" /></span> 
    <?php endif; ?>
     
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
        <img style="width: 50px;" src="<?php echo $this->baseUrl('/img/droite.png'); ?>" alt="page precedente" />
      </a> 
    <?php else: ?>
      <span class="disabled"><img style="width: 50px;" src="<?php echo $this->baseUrl('/img/droite.png'); ?>" alt="page precedente" /></span> 
    <?php endif; ?>
     
    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
        <img style="width: 50px;" src="<?php echo $this->baseUrl('/img/fin.png'); ?>" alt="page precedente" />
      </a>
    <?php else: ?>
      <span class="disabled"><img style="width: 50px;" src="<?php echo $this->baseUrl('/img/fin.png'); ?>" alt="page precedente" /></span>
    <?php endif; ?>
    <?php endif; ?>
</div>