<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('drh/pilote/'); ?>">
						Liste des heures des Pilotes
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('drh/ajouterpersonne'); ?>">
						Ajouter un pilote
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('drh/brevet'); ?>">
						Assigner des brevets
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>
