<h1>Nombres d'heures des pilotes et co-pilotes</h1>
<br /><br />
    <!--Filtre -->
    <table>
        <tr>
            <td><a href="<?php echo $this->baseUrl('drh/filtre/page/2'); ?>">
                    Afficher les personnes ayant dépassé le quota d'heure max
                </a>
            </td>
        </tr>
    </table>
<br /><br /><br />
<?php
$listePilote = $this->listePilote;
    $count = count($listePilote);
    ?>
    <?php
    if($count ==0) {echo'la liste est vide';}
    ?>
    <table id="listepilote">
        <?php
        for ($i = 1; $i <= $count; $i++) {
        ?>
            <tr>
                <td>
                    <?php echo " le pilote "; echo $listePilote[$i][0] . " " . $listePilote[$i][1];; ?>
                </td>
                <td>
                    <?php echo" à éffectué "; echo $listePilote[$i][2]; echo " vol";?>
                </td>
                <td>
                    <?php echo "soit un total de "; echo $listePilote[$i][3]; echo" heures de vol"; ?>
                </td>
            </tr>

        <?php
        }echo $this->paginator;
        ?>
    </table>
        <li>
            <a href="<?php echo $this->baseUrl('drh/index'); ?>">
                Revenir à l'accueil
            </a>
        </li>
