<center>
<?php 
$lesrevisions = $this->lesrevisions;
if(count($lesrevisions)>=1)
{?>

<table class="avion" id="tableauInfoVolMath">
	<thead>
		<tr>
			<th>Immatriculation</th>
			<th>Date mis en service</th>
			<th>Statut</th>
			<th>Modele</th>
			<th>Aeroport d'attache</th>
			<th>Localisation</th>
			<th>Date prévue</th>
			<th>Révisions</th>
		</tr>
	</thead>
	<tbody>
<?php 
	
	$avion = new Avion();
	$modele = new Modele();
	$aeroport = new Aeroport();
	foreach ($lesrevisions as $unerevision)
	{
		$lavion = $avion->selectOne($unerevision['idAvion']);
		$lemodele = $modele->selectOne($lavion[0]['idModele']);
		$laeroportDattache = $aeroport->selectOne($lavion[0]['idAeroportDattache']);
		$localisation = $aeroport->selectOne($lavion[0]['localisation']);
?>
		<tr>
			<td><?= $lavion[0]['numImmatriculation'] ;?></td>
			<td><?= $lavion[0]['dateMisEnService'] ;?></td>
			<td><?= ucfirst ($lavion[0]['statut']);?></td>
			<td><?= $lemodele[0]['nomModele']; ?></td>
			<td><?= $laeroportDattache[0]['nomAeroport'] ;?></td>
			<td><?= $localisation[0]['nomAeroport'] ;?></td>
			<td><?= $unerevision['datePrevue'] ;?></td>
			<td>
				<?php 
				if($unerevision['dateDebut'])
				{?>	
					<a href="/maintenance/gererrevision?idAvion=<?= $lavion[0]['idAvion'];?>&action=sortir">Sortir de révision</a>
				<?php }
				else 
				{
					if($lavion[0]['localisation'] == $lavion[0]['idAeroportDattache'])
					{
						$date = explode("-", $unerevision['datePrevue']);
		    			$datep = mktime(0,0,0,$date[1],$date[2],$date[0]);
		    			$today = time();
		    			if($datep > $today)
		    			{?>
							<a href="/maintenance/gererrevision?idAvion=<?= $lavion[0]['idAvion'];?>&action=mettre" onclick="return confirm('La date pévue n\'est pas pour maintenant, êtes-vous sûr de vouloir passer cet avion en révision ?');">Mettre en révision</a>
				<?php 	}
						else 
						{?>
							<a href="/maintenance/gererrevision?idAvion=<?= $lavion[0]['idAvion'] ;?>&action=mettre">Mettre en révision</a>
				<?php	}
					}
				}
				?>
			</td>
		</tr>
<?php }?>
	</tbody>
</table>
<?php }else{echo'Pas de révisions à gérer.';}?>
</center>
<div id="popupajoutavion" class="popup_block">
	<?php echo $this->formajoutavion;?>      
	<a href="#?w=500" rel="popupajoutavion" class="poplight">Ajouter un avion</a>     
</div>
<br /><br />
<div class ="imgRetour2">
	<a href="/maintenance/index">
		<img style="width:70px;" src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" />
	</a>
</div>