<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="#?w=500" rel="popupajoutavion" class="poplight">
						Ajouter un avion
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('maintenance/afficherrevision'); ?>">
						Gérer les révisions
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>
<center>
<div class="filtreStrategique">
<?php 
echo $this->filtre;
$lesavions = $this->lesavions;
if(count($lesavions)>=1)
{?>
</div>

<table class="avion" id="tableauInfoVolMath">
	<thead>
		<tr>
			<th></th>
			<th>Immatriculation</th>
			<th>Date mis en service</th>
			<th>Statut</th>
			<th>Modele</th>
			<th>Aeroport d'attache</th>
			<th>Localisation</th>
			<th>Révisions</th>
		</tr>
	</thead>
	<tbody>
<?php 
	$revision = new Revision();
	$modele = new Modele();
	$aeroport = new Aeroport();
	foreach ($lesavions as $unAvion)
	{
		$lemodele = $modele->selectOne($unAvion['idModele']);
		$laeroportDattache = $aeroport->selectOne($unAvion['idAeroportDattache']);
		$localisation = $aeroport->selectOne($unAvion['localisation']);
		$plannifie=$revision->isPlannifie($unAvion['idAvion']);
?>
		<tr>
	    	<td><a href="/maintenance/modifier?idAvion=<?= $unAvion['idAvion']; ?>"><img src="/img/outil.png" alt="modif"/></a></td>
			<td><?= $unAvion['numImmatriculation'] ;?></td>
			<td><?= $unAvion['dateMisEnService'] ;?></td>
			<td><?= ucfirst ($unAvion['statut']);?></td>
			<td><?= $lemodele[0]['nomModele']; ?></td>
			<td><?= $laeroportDattache[0]['nomAeroport'] ;?></td>
			<td><?= $localisation[0]['nomAeroport'] ;?></td>
			<td>
				<?php 
				if(count($plannifie)<1)
				{
					if($unAvion['statut']!='en révision')
					{
						if($unAvion['nbHeureVolDepuisGrandeRevision']>= $lemodele[0]['periodeGrandeRevision'])
						{?>
							<a href="/maintenance/plannifier?idAvion=<?= $unAvion['idAvion'] ;?>&statut=grande">Plannifier</a>
					<?php }
						else
						{
							if($unAvion['nbHeureVolDepuisPetiteRevision']>= $lemodele[0]['periodePetiteRevision'])
							{?>
								<a href="/maintenance/plannifier?idAvion=<?= $unAvion['idAvion'];?>&statut=petite">Plannifier</a>
						<?php }
						}
					 }
				}
				?>
			</td>
		</tr>
<?php }?>
	</tbody>
</table>
<br />
<?php }else{echo'Aucun résultat pour votre recherche';}?>
<div id="popupajoutavion" class="popup_block">
	<?php echo $this->formajoutavion;?>           
</div>
<?php if($lesavions != NULL){ echo $this->paginationControl($lesavions,'All', 'paginationcontroleavion.phtml');}?>
<br /><br /></center>
<div class ="imgRetour2">
	<a href="/">
		<img style="width:70px;" src="<?php echo $this->baseUrl('/img/retour.png'); ?>" alt="retour" />
	</a>
</div>