<?php 
//on récupère les infos du controlleur
$formulaire = $this->formulaire;
$lesAvions = $this->lesAvions;
//$lesAeroportsDeDepart = $this->lesAeroportsDeDepart;
//$lesAeroportsDArrivee = $this->lesAeroportsDArrivee;
//$lesJourEtDateDeVol = $this->lesJourEtDateDeVol;
//$duree = $this->duree;
$tableau = $this->tableau;
?>
<?php if(isset($lesAvions)){ ?>
<div id="tableauxSupprVol">	
	<table id="tableauTitreVol">
		<tr>
			<th >Avion à supprimer</th>
			<th >numero</th>
			<th ></th>
			<th ></th>
			<th ></th>
			<th ></th>
		</tr>
	</table>
	
	<?php echo $formulaire;?>
	
	<table id="tableauInfoVol">
	<?php   foreach ($lesAvions as $unAvion) { ?>
		<tr>
			<td><?php  echo $unAvion->numImmatriculation; ?></td>
	   </tr>
	<?php  }?>
	</table>
	<?php  }?>
	<?php 	if(isset($tableau))
			{
		  		foreach ($tableau as $clef=>$valeur) 
		  		{ 
 					echo $valeur.' a bien été supprimé <br />'; 
 				}
			} 
	?>
</div>
	<?php echo'<br /><br /><a href="'.$this->baseUrl('maintenance/index').'">Retour </a>';?>
	<?php if($lesAvions != NULL){ echo $this->paginationControl($lesAvions,'All', 'paginationcontroleavion.phtml');}?>