<?php 
//on récupère les infos du controlleur
$lesVolsAEnvoyer = $this->lesVolsAEnvoyer;
$lesLignesAEnvoyer = $this->lesLignesAEnvoyer;
$lesAvionsAEnvoyer = $this->lesAvionsAEnvoyer;
$lesFormulaires = $this->lesFormulaires;
?>

<div class="listeVolAfficher">
	<?php foreach($lesVolsAEnvoyer as $unVol) {  ?>
		<div class="unVolAfficher">
			 Le vol numero : <?php echo $unVol['idJournalDeBord']; ?><br/>
			 L'avion numero : <?php echo $lesAvionsAEnvoyer[$unVol['idJournalDeBord']]->numImmatriculation; ?><br/>
			 Aéroport d'arrivée : <?php echo $lesLignesAEnvoyer[$unVol['idJournalDeBord']]->aeroportArrivee; ?><br/>
			 Durée du vol : <?php echo $lesLignesAEnvoyer[$unVol['idJournalDeBord']]->dureeVol; ?><br/>
			 <?php echo $lesFormulaires[$unVol['idJournalDeBord']]; ?>
		</div>	
	<?php } ?>
</div>	