<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('technique/index'); ?>?valeur=decollage">
						Gérer les décollages
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('technique/index'); ?>?valeur=atterissage">
						Gérer les attérissages
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>