<div id="tableauxSupprVol">
	
	<table id="tableauTitreVol">
		<tr>
			<th >Vols a supprimer</th>
			<th >numero</th>
			<th >periodicite</th>
		</tr>
	</table>
	
	<?php echo $this->formulaire; ?>
	
	<table id="tableauInfoVol">
	<?php $lesVols = $this->lesVols; 
		  foreach($lesVols as $unVol) { ?>
		<tr>
			<td><?php echo $unVol->numVol; ?></td>
			<td><?php echo $unVol->periodicite; ?></td>
	   </tr>
	<?php } ?>
	
	</table>
	
</div>