<?php $lesVols = $this->lesVols; ?>

<table>
<tr>
	<th >id</th>
	<th >numero</th>
	<th >periodicite</th>
</tr>
<form method="post" action="<?php echo $this->baseUrl('strategique/index'); ?>?valeur=fermer" id="formulaireSuppression">
		
<?php foreach($lesVols as $unVol) { ?>
	<tr>
		<td><input type="checkbox" name="id<?php $unVol->idVol; ?>" id="id<?php $unVol->idVol; ?>" value="<?php $unVol->idVol; ?>" /></td>
		<td><?php echo $unVol->numVol; ?></td>
		<td><?php echo $unVol->periodicite; ?></td>
   </tr>
<?php } ?>

</table>
<input type="submit" name="btValider" id="btValider" value="Valider" />
</form>