<center>
	<table class="tablemenu">
		<tr>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('strategique/index/'); ?>?valeur=creer">
						Créer une ligne
					</a>
				</p>
			</td>
			<td>
				<p class="buttonSousMenu">
					<a href="<?php echo $this->baseUrl('strategique/index'); ?>?valeur=fermer">
						Fermer une ligne
					</a>
				</p>
			</td>
		</tr>
	</table>
</center>


<?php $tableau = $this->tableau; if(count($tableau) > 0){ ?>
<div id="volSupprime">
	<?php for ($i=0; $i<count($tableau); $i++) {?>
	<p>Le vol <u><?php echo $tableau[$i]; ?></u> a été supprimé. </p>
	<?php } ?>
</div>
<?php } ?>